name: install signore
description: copy signore binary from docker image
inputs:
  packages-token:
    description: GITHUB_TOKEN with access to signore package
    required: true
  signore-tag:
    description: package version to install
    required: true
    default: v0
outputs:
  signore-version:
    description: version of signore insalled
    value: ${{ steps.get-version.outputs.signore-version }}
runs:
  using: composite
  steps:
    - uses: docker/login-action@v1
      with:
        registry: ghcr.io
        username: ${{ github.actor }}
        password: ${{ inputs.packages-token }}
    - name: copy from image
      shell: bash
      run: |
        docker pull ghcr.io/hashicorp/signore:${{ inputs.signore-tag }}
        CONTAINER_ID=$(docker create ghcr.io/hashicorp/signore:${{ inputs.signore-tag }})
        docker cp $CONTAINER_ID:/usr/bin/signore /usr/local/bin/signore
        docker rm -f $CONTAINER_ID
    - id: get-version
      shell: bash
      run: |
        SIGNORE_VERSION=$(signore)
        echo "::set-output name=signore-version::$SIGNORE_VERSION"
